/** Bundled mock fixtures. Loaded lazily via import.meta.glob so they land in a
 *  separate chunk and never weigh down the initial bundle. These are the
 *  fallback data source when VITE_GOLAVO_API is unset (the default). */
import type {
  CalibrationSummary,
  CommentatorsNotebook,
  EvalSummary,
  ForecastArtifact,
  MatchRow,
  NotebookResponse,
  SchemaVersion,
} from "../lib/contract";

const forecastModules = import.meta.glob<ForecastArtifact>("./forecasts/*.json", {
  import: "default",
});

const notebookModules = import.meta.glob<CommentatorsNotebook>("./notebooks/*.json", {
  import: "default",
});

// Sample AI narratives — used ONLY when a test flag is set (golavo-ai-fixture),
// so the redesigned AI read is visually testable in mock mode. Never returned
// by default; the panel's sample-data callout stays visible on top of any
// fixture render, keeping the honesty rule ("the UI never fabricates a
// narration") intact.
const narrativeModules = import.meta.glob<unknown>("./narratives/*.json", {
  import: "default",
});

/** All mock artifacts, sorted newest-first by seal time. */
export async function loadMockForecasts(): Promise<ForecastArtifact[]> {
  const loaded = await Promise.all(Object.values(forecastModules).map((imp) => imp()));
  return loaded.sort((a, b) =>
    b.forecast.sealed_at_utc.localeCompare(a.forecast.sealed_at_utc),
  );
}

export async function loadMockForecast(id: string): Promise<ForecastArtifact | null> {
  const all = await loadMockForecasts();
  return all.find((a) => a.artifact_id === id) ?? null;
}

/** A notebook mock is keyed by artifact id via its filename (notebooks/<id>.json).
 *  Absent one, we return an honest unavailable envelope — never fabricated facts. */
export async function loadMockNotebook(id: string): Promise<NotebookResponse> {
  const entry = Object.entries(notebookModules).find(([path]) => path.endsWith(`/${id}.json`));
  if (!entry) return { artifact_id: id, available: false, notebook: null };
  return { artifact_id: id, available: true, notebook: await entry[1]() };
}

/** A sample narrative keyed by subject id (narratives/<id>.json), or null when
 *  absent. Only consulted behind the golavo-ai-fixture test flag. */
export async function loadMockNarrative(id: string): Promise<unknown | null> {
  const entry = Object.entries(narrativeModules).find(([path]) => path.endsWith(`/${id}.json`));
  if (!entry) return null;
  return entry[1]();
}

export async function loadMockEval(): Promise<EvalSummary> {
  const mod = await import("./eval-summary.json");
  return mod.default as unknown as EvalSummary;
}

/** Synthetic calibration record, generated by the real aggregator over the
 *  synthetic sample-artifact ledger (scripts/generate_sample_artifacts.py). */
export async function loadMockCalibration(): Promise<CalibrationSummary> {
  const mod = await import("./calibration.json");
  return mod.default as unknown as CalibrationSummary;
}

export interface MockMatches {
  schema_version: SchemaVersion;
  matches: MatchRow[];
}

/** Synthetic match directory, generated in lockstep with the sample artifacts
 *  by scripts/generate_sample_artifacts.py. Every row carries a synthetic
 *  source_id so it can never be mistaken for real data. */
export async function loadMockMatches(): Promise<MockMatches> {
  const mod = await import("./matches.json");
  return mod.default as unknown as MockMatches;
}
