/** Bundled mock fixtures. Loaded lazily via import.meta.glob so they land in a
 *  separate chunk and never weigh down the initial bundle. These are the
 *  fallback data source when VITE_GOLAVO_API is unset (the default). */
import type {
  CalibrationSummary,
  CommentatorsNotebook,
  EvalSummary,
  ForecastArtifact,
  NotebookResponse,
} from "../lib/contract";

const forecastModules = import.meta.glob<ForecastArtifact>("./forecasts/*.json", {
  import: "default",
});

const notebookModules = import.meta.glob<CommentatorsNotebook>("./notebooks/*.json", {
  import: "default",
});

/** All mock artifacts, sorted newest-first by seal time. */
export async function loadMockForecasts(): Promise<ForecastArtifact[]> {
  const loaded = await Promise.all(Object.values(forecastModules).map((imp) => imp()));
  return loaded.sort((a, b) =>
    b.forecast.sealed_at_utc.localeCompare(a.forecast.sealed_at_utc),
  );
}

export async function loadMockForecast(id: string): Promise<ForecastArtifact | null> {
  const all = await loadMockForecasts();
  return all.find((a) => a.artifact_id === id) ?? null;
}

/** A notebook mock is keyed by artifact id via its filename (notebooks/<id>.json).
 *  Absent one, we return an honest unavailable envelope — never fabricated facts. */
export async function loadMockNotebook(id: string): Promise<NotebookResponse> {
  const entry = Object.entries(notebookModules).find(([path]) => path.endsWith(`/${id}.json`));
  if (!entry) return { artifact_id: id, available: false, notebook: null };
  return { artifact_id: id, available: true, notebook: await entry[1]() };
}

export async function loadMockEval(): Promise<EvalSummary> {
  const mod = await import("./eval-summary.json");
  return mod.default as unknown as EvalSummary;
}

/** Synthetic calibration record, generated by the real aggregator over the
 *  synthetic sample-artifact ledger (scripts/generate_sample_artifacts.py). */
export async function loadMockCalibration(): Promise<CalibrationSummary> {
  const mod = await import("./calibration.json");
  return mod.default as unknown as CalibrationSummary;
}
