import type { ForecastArtifact } from "../lib/contract";
import { FAMILY_LABELS, HORIZON_LABELS } from "../lib/contract";
import { utc } from "../lib/format";
import { SealIcon } from "./icons";
import { Hash } from "./primitives";

/** The seal: the immutable commitment recorded before kickoff. Every field here
 *  is part of what payload_sha256 covers — change any input and the hash changes. */
export function SealStamp({ artifact }: { artifact: ForecastArtifact }) {
  const { forecast, model, provenance } = artifact;
  return (
    <section className="panel seal" aria-labelledby="seal-h">
      <SealEmblem />
      <div className="panel__head">
        <SealIcon size={17} style={{ color: "var(--gold)" }} />
        <h2 id="seal-h">Seal stamp</h2>
      </div>
      <div className="panel__body">
        <dl className="kv kv--seal">
          <dt>Sealed at</dt>
          <dd className="num">{utc(forecast.sealed_at_utc)}</dd>

          <dt>Horizon</dt>
          <dd>{HORIZON_LABELS[forecast.horizon]} <span className="muted small">before kickoff</span></dd>

          <dt>Model</dt>
          <dd>
            {FAMILY_LABELS[model.family]}{" "}
            <span className="muted mono small">{model.model_id} · v{model.version}</span>
          </dd>

          <dt>Seed</dt>
          <dd className="mono num">{model.seed}</dd>

          <dt>Code git sha</dt>
          <dd><Hash value={model.code_git_sha} /></dd>

          <dt>Params hash</dt>
          <dd><Hash value={model.params_hash} /></dd>

          <dt>Payload sha256</dt>
          <dd><Hash value={provenance.payload_sha256} /></dd>
        </dl>
        <p className="small dim" style={{ marginTop: ".9rem" }}>
          Generated by {provenance.generator}. Deterministic: identical inputs and seed
          reproduce this artifact byte-for-byte.
        </p>
      </div>
    </section>
  );
}

function SealEmblem() {
  return (
    <svg className="seal__emblem" viewBox="0 0 100 100" aria-hidden focusable="false">
      <circle cx="50" cy="50" r="30" fill="none" stroke="var(--gold-brand)" strokeWidth="2" />
      <circle cx="50" cy="50" r="21" fill="none" stroke="var(--gold-line)" strokeWidth="1.4" />
      <circle cx="50" cy="50" r="10" fill="var(--red)" opacity="0.55" />
    </svg>
  );
}
